spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456


logging:
  level:
    root: warn
    com.star: debug
  file:
    name: log/blog-pro.log
server:
  port: 8081
