spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

pagehelper:                #分页插件
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:

logging:
  level:
    root: info
    com.wx: debug
  file:
    name: log/blog-dev.log

#server:
#  port: 443
#  ssl:
#    key-store: 4451865_www.xnpng.top.pfx
#    key-store-password: 7Dv8j4NP
